service:
  - docker

before_install:
  - docker-compose build
  - docker-compose up

script:
    - docker run -e CI=true myapp-server npm run test

deploy:
  provider: heroku
  api_key: 
    secure: ••••••••••••••••
  on:
    branch: master