service:
  - docker

# before_install:
#   - docker-compose build
#   - docker-compose up

# script:
#     - docker run -e CI=true myapp-server npm run test

deploy:
  provider: heroku
  api_key: 
    secure: $HEROKU_API_KEY
  on:
    branch: master